version: '3.3'

services:
  mysql:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes: 
      - mysql:/var/lib/mysql
    # env_file: ./.env
    # environment: 
    #    - MYSQL_USER=example
    #    - MYSQL_ROOT_PASSWORD=example
    #    - MYSQL_DATABASE=db
            # - MYSQL_ALLOW_EMPTY_PASSWORD= 1
    ports: 
      - 3306:3306
      - 33060:33060
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links:
        - mysql 
    depends_on: 
      - mysql
volumes:
  mysql:

   app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    image: node-mysql-app
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    volumes: 
      - ./app:/app
      - app/node_modules
    depends_on:
      - mysql
    stdin_open: true
    tty: true